# pnpm-workspace.yaml
packages:
    - "packages/webdriver-image-comparison"
    - "packages/visual-service"
    - "packages/ocr-service"
    - "packages/visual-reporter"
    - "packages/visual-remix-reporter"
