name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - alpha

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🌲 Setup Git
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: NPM Setup
        run: |
          npm set registry "https://registry.npmjs.org/"
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm whoami

      - name: ∽ Git Setup
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 🧩 Install Dependencies
        run: pnpm pnpm.install.workaround

      - name: Set RELEASE_TAG
        run: echo "RELEASE_TAG=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV

      - name: 🏗️ Build
        id: build-the-mono-repo
        run: |
          pnpm build

      - name: 📣 Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release --tag ${{ env.RELEASE_TAG }}
          setupGitUser: true
          commit: "chore: release [skip ci]"
