name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v2

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 🏗️ Build
        working-directory: ./
        run: pnpm build

      - name: 🧪 Run linting and unit tests
        working-directory: ./
        run: pnpm test

      - name: 😶‍🌫️ 🕸️ Run Web e2e tests
        working-directory: ./
        env:
          SAUCE_USERNAME_WDIO_ICS: ${{ secrets.SAUCE_USERNAME_WDIO_ICS }}
          SAUCE_ACCESS_KEY_WDIO_ICS: ${{ secrets.SAUCE_ACCESS_KEY_WDIO_ICS }}
          BUILD_PREFIX: true
        run: pnpm test.saucelabs.web --maxConcurrency=25

      - name: 📤 Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: web-logs
          path: |
            logs/*.log
            .tmp/
            !.tmp/checkActual/
            !.tmp/saveActual/
            !.tmp/testDiff/

  ci-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v2

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 🏗️ Build
        working-directory: ./
        run: pnpm build

      - name: 🧪 Run linting and unit tests
        working-directory: ./
        run: pnpm test

      - name: 😶‍🌫️ 📱 Run App e2e tests
        working-directory: ./
        env:
          SAUCE_USERNAME_WDIO_ICS: ${{ secrets.SAUCE_USERNAME_WDIO_ICS }}
          SAUCE_ACCESS_KEY_WDIO_ICS: ${{ secrets.SAUCE_ACCESS_KEY_WDIO_ICS }}
          BUILD_PREFIX: true
        run: pnpm test.saucelabs.app --maxConcurrency=5

      - name: 📤 Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: app-logs
          path: |
            logs/*.log
            .tmp/
            !.tmp/checkActual/
            !.tmp/saveActual/
            !.tmp/testDiff/
